### PR TITLE
Fix CI by reordering tests

### PR DESCRIPTION
**Pull request by Jongy**
## Description
Attempts to fix:
* [x] The weird dl error that we have been having in the last 3 weeks (for example https://github.com/Granulate/gprofiler/runs/4829130163?check_suite_focus=true). Exception is `AssertionError: unexpected 'grep' exit code: 127, stdout b'' stderr b"Inconsistency detected by ld.so: dl-open.c: 560: dl_open_worker: Assertion `_dl_debug_initialize (0, args->nsid)->r_state == RT_CONSISTENT' failed!\n"`.
* [x] ~~Occasional PyPerf errors (for example https://github.com/Granulate/gprofiler/runs/4829130238?check_suite_focus=true). Exception is `UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbc in position 1678190: invalid start byte` (as if PyPerf outputs invalid textual data... Happens only when testing against Python 3.10, so I feel like it's a bug in the Python 3.10 support)~~ with the added print I understood the source of the issue (see bad data in https://github.com/Granulate/gprofiler/runs/5258558141?check_suite_focus=true), will fix[ in another PR](https://github.com/Granulate/gprofiler/pull/300).

### CODE REVIEW

**Comment by Jongy** [comment]
Heh, this seems to have fixed the issue.... Trying again.

**Comment by Jongy** [comment]
This fixes the CI + adds a print of the failing data of PyPerf (when it fails)

**Review by adi-benz — APPROVED** [review]
I don't like that we're reordering tests instead of actually fixing the problem, but I guess it's better then nothing / better than investing too much time into it

**Comment by Jongy** [comment]
> I don't like that we're reordering tests instead of actually fixing the problem, but I guess it's better then nothing / better than investing too much time into it

I don't like it much either, but we've already spent a couple of hours on it (and I have personally spent, haha) with no conclusion. I am interested about its source as I truly don't understand how / why t could happen. You can take a couple of hours to look at it if you'd like.

**Pull request merged**
