### PR TITLE
Upgrade perf to base on Linux 5.18

### PR DESCRIPTION
**Pull request by Jongy**

### CODE REVIEW

**Comment by Jongy** [comment]
Haven't tested yet though.

I hope this resolves
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000000000059a114 in machine__process_bpf_event_load (sample=<optimized out>, event=<optimized out>, machine=0x20574d0) at util/bpf-event.c:58

```

**Review by michelhe — COMMENTED** [review]
You think the CI is a good-enough cover ?

**Comment by Jongy** [comment]
> You think the CI is a good-enough cover ?

No, I added tests in https://github.com/Granulate/gprofiler/pull/420, let's merge them first.

**Comment by Jongy** [comment]
Oof no "update branch" button lol

**Comment by Jongy** [comment]
@michelhe tests passed

**Review by michelhe — APPROVED** [review]
🥂

**Pull request merged**
