### PR TITLE
bugfix: gProfiler excessive restarts when run in a container and failing to grab the mutex

### PR DESCRIPTION
**Pull request by tomersa**
Change exit code to 0 when failing to grab the mutex. This help gprofiler container avoid
excessive restarts when running using K8s or docker

## Description
Exiting with exit code 0 when failing to grab the mutex. 

## Checklist:
- [ ] I have read the **CONTRIBUTING** document.
- [x] I have updated the relevant documentation.
- [ ] I have added tests for new logic.

### CODE REVIEW

**Comment by Jongy** [comment]
Also change the documentation to use `--restart=on-failure`?

**Comment by tomersa** [comment]
I've also made a maximum of 10 retries by default FYI

**Comment by Jongy** [comment]
> I've also made a maximum of 10 retries by default FYI

Cool. I wasn't aware of this feature. Can you please check from which Docker version is it available? (we refrained from adding `--pull=always` because it's too new and it caused `docker run` to fail in many servers; hence it shouldn't be in the "standard" command)

**Comment by tomersa** [comment]
> > I've also made a maximum of 10 retries by default FYI
> 
> Cool. I wasn't aware of this feature. Can you please check from which Docker version is it available? (we refrained from adding `--pull=always` because it's too new and it caused `docker run` to fail in many servers; hence it shouldn't be in the "standard" command)

Couldn't find it. I guess it's old enough to be used here.

**Review by Jongy — APPROVED** [review]

**Comment by tomersa** [comment]
@Jongy I resolved conflict in README please reapprove.

**Review by Jongy — APPROVED** [review]

**Comment by tomersa** [comment]
@Jongy You know what are this problems in the CI?
GProfiler CI / test (3.6) (pull_request) Failing after 41s — test (3.6)

It fails on async_profiler_env.sh

**Comment by Jongy** [comment]
> @Jongy You know what are this problems in the CI?
> GProfiler CI / test (3.6) (pull_request) Failing after 41s — test (3.6)
> 
> It fails on async_profiler_env.sh

Nope. Will check in the next PR

**Pull request merged**
