### PR TITLE
Add AWS Fargate running instructions

### PR DESCRIPTION
**Pull request by Jongy**
Title says it all.

Based on https://github.com/Granulate/gprofiler/pull/174

### CODE REVIEW

**Comment by alonbentamar** [comment]
Perhaps include an example task definition with all of the new parameters?

**Review by alonbentamar — COMMENTED** [review]
left a comment

**Comment by Jongy** [comment]
> Perhaps include an example task definition with all of the new parameters?

I thought about it, but it's long and most parameters are irrelevant so I think it will just confuse the users.

**Review by alonbentamar — DISMISSED** [review]
LGMT, fix conflicts

**Review by alonbentamar — DISMISSED** [review]

**Comment by Jongy** [comment]
Added a few more notes

**Review by alonbentamar — DISMISSED** [review]

**Review by alonbentamar — APPROVED** [review]

**Pull request merged**
