### PR TITLE
Don't install unneeded packages when building perf

### PR DESCRIPTION
**Pull request by d3dave**
## Description
The build installs `texlive-*-doc` packages which amount to 500MB+ download. For example, `texlive-latex-extra-doc`:
```
Get:359 http://archive.ubuntu.com/ubuntu xenial/main amd64 texlive-latex-extra-doc all 2015.20160320-1 [338 MB]
```
On a slow/metered connection this is a considerable barrier to building the image. We don't need these packages.

## How Has This Been Tested?
Build succeeds, perf still works. I don't think perf requires any of the recommended packages besides what's already specified.

### CODE REVIEW

**Comment by d3dave** [comment]
Here's the original list of additional recommended packages (excluding ones we already require):
```
patch
less
rsync
<ssh-client>
dblatex
docbook-utils
libxml2-utils
xmlto
libssl-doc
bzip2-doc
```

**Comment by Jongy** [comment]
Very nice!

To make sure `perf` really hasn't changed, you can run `perf test` and verify the outputs match. That's what I did when I worked on https://github.com/Granulate/gprofiler/pull/69.

**Comment by d3dave** [comment]
> Very nice!
> 
> To make sure `perf` really hasn't changed, you can run `perf test` and verify the outputs match. That's what I did when I worked on #69.

Output is identical.

**Comment by Jongy** [comment]
kk

**Review by Jongy — APPROVED** [review]

**Pull request merged**
