### PR TITLE
Avoid using subprocess.Popen.wait()

### LINKED ISSUE #744: python: ebpf: _terminate() blocking
I got this dump from a test deployment of a gProfiler 1.19.0, which became stuck.
```
Thread 16815 (idle): "ThreadPoolExecutor-0_3"
    _try_wait (subprocess.py:1901)
        Arguments:
            self: <Popen at 0x7f92f05ccd60>
            wait_flags: 0
    _wait (subprocess.py:1943)
        Arguments:
            self: <Popen at 0x7f92f05ccd60>
            timeout: None
    wait (subprocess.py:1209)
        Arguments:
            self: <Popen at 0x7f92f05ccd60>
            timeout: None
    _terminate (python_ebpf.py:254)
        Arguments:
            self: <PythonEbpfProfiler at 0x7f92f8b0b010>
        Locals:
            code: None
    _dump (python_ebpf.py:221)
        Arguments:
            self: <PythonEbpfProfiler at 0x7f92f8b0b010>
        Locals:
            process: <Popen at 0x7f92f05ccd60>
    snapshot (python_ebpf.py:227)
        Arguments:
            self: <PythonEbpfProfiler at 0x7f92f8b0b010>
    snapshot (python.py:403)
        Arguments:
            self: <PythonProfiler at 0x7f92f8b0add0>
    run (thread.py:58)
        Arguments:
            self: <_WorkItem at 0x7f92f028aa10>
    _worker (thread.py:83)
        Arguments:
            executor_reference: <weakref.ReferenceType at 0x7f92f8b97fb0>
            work_queue: <_queue.SimpleQueue at 0x7f92f8b1f830>
            initializer: None
            initargs: ()
        Locals:
            work_item: <_WorkItem at 0x7f92f028aa10>
```

gProfiler tried to stop PyPerf, it sent SIGTERM and PyPerf indeed exited with SIGTERM. However, gProfiler remains blocked in the `wait` function. Not sure if it's a bug in python stdlib/gprofiler/kernel lol. Why would wait block if PyPerf truly exited?

### PR DESCRIPTION
**Pull request by Jongy**
Possiblyt fixes #744 - avoids all `subprocess.Popen.wait()` calls, which are possibly deadlocking.

### CODE REVIEW

**Comment by Jongy** [comment]
Failure is not related.

**Review by d3dave — CHANGES_REQUESTED** [review]
spelling

**Comment by Jongy** [comment]
> spelling

I'll go over the text again, anything specific though? :sweat_smile:

**Comment by Jongy** [comment]
While this is a good change, I understand it won't solve the case I described in the ticket, which was a process that has pending output + was killed due signal + wait() is blocking. IIRC PyPerf does not handle SIGTERM - so it is killed immediately, and hence, wait() should not block (if PyPerf was handling SIGTERM then we could say it's *trying* to exit but blocking on pipe writes).

In any case... it's a good change so I'm merging anyway.

**Pull request merged**
