### PR TITLE
java: Profile Zing with AP & refactor version checks

### PR DESCRIPTION
**Pull request by Jongy**
1. Profile Zing if Zing VM > 18
2. Don't profile HS 6 - it crashes
3. Refactor & document version checks

### CODE REVIEW

**Comment by adi-benz** [comment]
Is this tested?

**Comment by Jongy** [comment]
> Is this tested?

Ofc. Tested on HS and Zing 22 (didn't test on old Zing tho, I don't have one at hand. I'll patch the checked version to 23 and make sure it now fails)

**Comment by Jongy** [comment]
Doing a few more checks & refactors, will update here

**Comment by Jongy** [comment]
@adi-benz ready

**Comment by Jongy** [comment]
See PR desc as well

**Review by adi-benz — APPROVED** [review]

**Comment by Jongy** [comment]
```
FAILED tests/test_executable.py::test_executable[False-php-phpspy] - docker.e...
```

unrelated failure

**Pull request merged**
