### PR TITLE
Update rbspy fork (0.7.0)

### PR DESCRIPTION
**Pull request by michelhe**

### CODE REVIEW

**Review by Jongy — APPROVED** [review]

**Review by Jongy — CHANGES_REQUESTED** [review]
.

**Comment by Jongy** [comment]
Add a tag and keep the branch pointing at the the previous commit

**Review by Jongy — APPROVED** [review]

**Comment by michelhe** [comment]
```tests/test_executable.py::test_from_executable[True-ruby] FAILED         [100%]```
@Jongy Seems to fail over pgrep-maps again, the pgrep maps for python return an err code since no python processes can be found

**Comment by michelhe** [comment]
> `tests/test_executable.py::test_from_executable[True-ruby] FAILED [100%]`
> @Jongy Seems to fail over pgrep-maps again, the pgrep maps for python return an err code since no python processes can be found

NVM, I see this race is fixed in 6181f2f, lets merge this before we version bump

**Comment by Jongy** [comment]
Can merge

**Comment by michelhe** [comment]
> Can merge

Async profiler build fails because it detects the download is too slow? LMAO

**Pull request merged**
