### PR TITLE
perf: Replace [unknown] symbols with the DSO path

### PR DESCRIPTION
**Pull request by Jongy**
## Description
Repalce `[unknown]` symbols in the `perf script` output with their DSO name. This is roughly the logic done here: https://github.com/brendangregg/FlameGraph/blob/a258e78f17abdf2ce21c2515cfe8306a44774e2a/stackcollapse-perf.pl#L275

## Motivation and Context
If we don't have the symbol name, at least we could have the DSO path.

## How Has This Been Tested?
I ran the profiler locally and verified that `[unknown]` symbols are replaced with their DSO. _Some_ of the unknowns remain unknowns (because the DSO was unknown as well...)

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [x] I have updated the relevant documentation.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by Jongy** [comment]
@DanielShaulov , I benched this with the following script:

```
from __future__ import annotations
from collections import Counter
import re
import sys
from pathlib import Path

if sys.argv[1] == "new":
    FRAME_REGEX = re.compile(r"^\s*[0-9a-f]+ (.*) \((.*)\)$")

    def collapse_stack(stack: str, comm: str) -> str:
        """
        Collapse a single stack from "perf".
        """
        funcs = [comm]
        for line in reversed(stack.splitlines()):
            m = FRAME_REGEX.match(line)
            assert m is not None, f"bad line: {line}"
            sym, dso = m.groups()
            if sym == "[unknown]":
                sym = dso
            # append kernel annotation
            elif "kernel" in dso or "vmlinux" in dso:
                sym += "_[k]"
            funcs.append(sym)
        return ";".join(funcs)

elif sys.argv[1] == "old":
    def collapse_stack(stack: str, comm: str) -> str:
        """
        Collapse a single stack from "perf".
        """
        funcs = [comm]
        for line in reversed(stack.splitlines()):
            # example line:
            # ffffffff81082227 mmput+0x57 ([kernel.kallsyms])
            words = line.split()
            sym = words[1].split("+")[0]
            # append kernel annotation
            if "kernel" in words[-1] or "vmlinux" in words[-1]:
                sym += "_[k]"
            funcs.append(sym)
        return ";".join(funcs)


SAMPLE_REGEX = re.compile(
    r"\s*(?P<comm>.+?)\s+(?P<pid>[\d-]+)/(?P<tid>[\d-]+)(?:\s+\[(?P<cpu>\d+)])?\s+(?P<time>\d+\.\d+):\s+"
    r"(?:(?P<freq>\d+)\s+)?(?P<event_family>[\w-]+):(?:(?P<event>[\w-]+):)?(?P<suffix>[^\n]*)(?:\n(?P<stack>.*))?",
    re.MULTILINE | re.DOTALL,
)


def parse_perf_script(script: str):
    for sample in script.split("\n\n"):
        try:
            if sample.strip() == "":
                continue
            if sample.startswith("#"):
                continue
            match = SAMPLE_REGEX.match(sample)
            if match is None:
                raise Exception("Failed to match sample")
            yield match.groupdict()
        except Exception:
            logger.exception(f"Error processing sample: {sample}")


def merge_perfs(perf_all: Iterable[Mapping[str, str]], process_perfs: Mapping[int, Mapping[str, int]]) -> str:
    per_process_samples: MutableMapping[int, int] = Counter()
    new_samples: MutableMapping[str, int] = Counter()
    process_names = {}
    for parsed in perf_all:
        try:
            pid = int(parsed["pid"])
            if pid in process_perfs:
                per_process_samples[pid] += 1
                process_names[pid] = parsed["comm"]
            elif parsed["stack"] is not None:
                new_samples[collapse_stack(parsed["stack"], parsed["comm"])] += 1
        except Exception:
            logger.exception(f"Error processing sample: {parsed}")

    for pid, perf_all_count in per_process_samples.items():
        process_stacks = process_perfs[pid]
        process_perf_count = sum(process_stacks.values())
        if process_perf_count > 0:
            ratio = perf_all_count / process_perf_count
            for stack, count in process_stacks.items():
                full_stack = ";".join([process_names[pid], stack])
                new_samples[full_stack] += round(count * ratio)

    return "\n".join((f"{stack} {count}" for stack, count in new_samples.items()))


import timeit

data = Path(sys.argv[2]).read_text()

print(timeit.timeit("merge_perfs(parse_perf_script(data), [])", number=50, globals=globals()))
```

The input & results:
```
$ wc -l perf.script
330168 perf.script
$ python3 bench_collapser.py new perf.script
15.064044358005049
$ python3 bench_collapser.py old perf.script
10.984822925005574
```

I'll try to revert the regex and do something else, that is cheaper.

**Comment by Jongy** [comment]
I wrote it as:
```
def collapse_stack(stack: str, comm: str) -> str:
    """
    Collapse a single stack from "perf".
    """
    funcs = [comm]
    for line in reversed(stack.splitlines()):
        # faster than parsing with a regex :/
        # for future reference, the relevant regex is r"^\s*[0-9a-f]+ (.*) \((.*)\)$"
        _, rest = line.lstrip().split(" ", maxsplit=1)
        sym, dso = rest.rsplit(" (", maxsplit=1)
        sym = sym.rsplit('+', maxsplit=1)[0]

        if sym == "[unknown]":
            sym = dso[:-1]  # strip last ')'
        # append kernel annotation
        elif "kernel" in dso or "vmlinux" in dso:
            sym += "_[k]"
        funcs.append(sym)
    return ";".join(funcs)
```
This benches as 12.5s~, which is better than 15 but the code is awful and might be buggy in some edge cases.

I don't think it's worth it - let's go with the regex here, and optimize this thing when it becomes a burden. @DanielShaulov wdyt

**Review by DanielShaulov — APPROVED** [review]
@Jongy - Yea, regex should be fine for now I think

**Comment by Jongy** [comment]
```
 thread_queue;clock_gettime@GLIBC_2.2.5;__vdso_clock_gettime 16
-thread_queue;std::vector<std::pair<long, 14
+thread_queue;std::vector<std::pair<long, work_item*>, std::allocator<std::pair<long, work_item*> > >::_M_erase 5
 thread_queue;__errno_location 4
```
The regex is a good call, anyway :) It fixed some stacks on my machine. Basically all C++ stacks were broken.

**Comment by Jongy** [comment]
Will merge after this release.

**Review by DanielShaulov — APPROVED** [review]

**Pull request merged**
