### PR TITLE
java: Build async-profiler with -static-libstdc++

### PR DESCRIPTION
**Pull request by Jongy**
## Description
Build async-profiler with `-static-libstdc++` to avoid the libstd++ dependency.

Needs https://github.com/Granulate/gprofiler/pull/137

## Related Issue
Possibly resolves https://github.com/Granulate/gprofiler/issues/136

## Motivation and Context
Allow async-profiler to be loaded also in environments without `libstdc++.so`.

## How Has This Been Tested?
* [x] CI tested my assumption that AP built on `centos:7` works fine on `centos:6` machines (old glibc compatibility). This assumption might be false, in which case I'll use devtoolset to get a newer GCC (default GCC of `centos:6` doesn't have `-static-libstdc++`)
* [x] ~~Test it on an environment where I removed `libstdc++.so`, thus old gProfiler won't work (will fail with the same error from #136 ), and this mew build will work.~~  ~~I can't really reproduce this - since Java itself uses libstdc++, it's already loaded in the process, anyway, so it won't matter if I deleted it. I don't understand how the state of #136 can happen (well, Java itself was compiled with `-static-libstdc++`?)~~ See https://github.com/Granulate/gprofiler/pull/139#issuecomment-879009012
* [x] Test on real CentOS 6 (also with 2.6 kernel)

## Checklist:
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have updated the relevant documentation.
- [ ] I have added tests for new logic.

### CODE REVIEW

**Review by liorgorb — APPROVED** [review]

**Review by liorgorb — APPROVED** [review]

**Comment by Jongy** [comment]
I installed `8.0.292.hs-adpt` via sdkman, (`sdk install java 8.0.292.hs-adpt`). It has no dependency on `libstdc++.so`. So I ran a Java app with it, and removed `/usr/lib/x86_64-linux-gnu/libstdc++.so.6`.

Result before (on master):
```
[2021-07-13 11:27:41,786] DEBUG: gprofiler.utils: Running command: (/app/gprofiler/resources/java/jattach 935723 load /tmp/gprofiler_tmp/async-profiler-v2.0g3/libasyncProfiler.so true start,event=itimer,file=/tmp/gprofiler_tmp/tmpt8_s95r_/async-profiler-935723.output,collapsed,ann,sig,interval=90909090,framebuf=2000000,log=/tmp/gprofiler_tmp/tmpt8_s95r_/async-profiler-935723.log)
[2021-07-13 11:27:41,809] DEBUG: gprofiler.utils: (['/app/gprofiler/resources/java/jattach', '935723', 'load', '/tmp/gprofiler_tmp/async-profiler-v2.0g3/libasyncProfiler.so', 'true', 'start,event=itimer,file=/tmp/gprofiler_tmp/tmpt8_s95r_/async-profiler-935723.output,collapsed,ann,sig,interval=90909090,framebuf=2000000,log=/tmp/gprofiler_tmp/tmpt8_s95r_/async-profiler-935723.log']) exit code: 255
[2021-07-13 11:27:41,809] DEBUG: gprofiler.utils: (['/app/gprofiler/resources/java/jattach', '935723', 'load', '/tmp/gprofiler_tmp/async-profiler-v2.0g3/libasyncProfiler.so', 'true', 'start,event=itimer,file=/tmp/gprofiler_tmp/tmpt8_s95r_/async-profiler-935723.output,collapsed,ann,sig,interval=90909090,framebuf=2000000,log=/tmp/gprofiler_tmp/tmpt8_s95r_/async-profiler-935723.log']) stdout: b'Connected to remote JVM\nJVM response code = -1\n\n'
[2021-07-13 11:27:41,809] WARNING: gprofiler.java: async-profiler DSO was not loaded into 935723
[2021-07-13 11:27:41,810] ERROR: gprofiler.profiler_base: JavaProfiler: failed to profile process 935723
Traceback (most recent call last):
  File "/app/gprofiler/profiler_base.py", line 111, in snapshot
    result = future.result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/app/gprofiler/java.py", line 306, in _profile_process
    return self._profile_ap_process(ap_proc)
  File "/app/gprofiler/java.py", line 309, in _profile_ap_process
    started = ap_proc.start_async_profiler(self._interval)
  File "/app/gprofiler/java.py", line 212, in start_async_profiler
    self._run_async_profiler(start_cmd)
  File "/app/gprofiler/java.py", line 204, in _run_async_profiler
    raise JattachException(e.returncode, e.cmd, e.stdout, e.stderr, self.process.pid, ap_log) from None
gprofiler.java.JattachException: Command '['/app/gprofiler/resources/java/jattach', '935723', 'load', '/tmp/gprofiler_tmp/async-profiler-v2.0g3/libasyncProfiler.so', 'true', 'start,event=itimer,file=/tmp/gprofiler_tmp/tmpt8_s95r_/async-profiler-935723.output,collapsed,ann,sig,interval=90909090,framebuf=2000000,log=/tmp/gprofiler_tmp/tmpt8_s95r_/async-profiler-935723.log']' returned non-zero exit status 255. 
stdout: b'Connected to remote JVM\nJVM response code = -1\n\n'
stderr: b''
Java PID: 935723
async-profiler log:
(empty)
```

and on this branch, it works fine :)

**Comment by Jongy** [comment]
Bleh, doesn't work on a real CentOS 6:
```
$ ldd /tmp/gprofiler_tmp/async-profiler-v2.0g4/libasyncProfiler.so 
/tmp/gprofiler_tmp/async-profiler-v2.0g4/libasyncProfiler.so: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /tmp/gprofiler_tmp/async-profiler-v2.0g4/libasyncProfiler.so)
	linux-vdso.so.1 =>  (0x00007ffe337e1000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007fa79a5b1000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fa79a394000)
	librt.so.1 => /lib64/librt.so.1 (0x00007fa79a18b000)
	libm.so.6 => /lib64/libm.so.6 (0x00007fa799f07000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fa799cf1000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fa79995c000)
	/lib64/ld-linux-x86-64.so.2 (0x0000556bd9219000)
$ cat /etc/centos-release
CentOS release 6.10 (Final)
```

**Comment by Jongy** [comment]
Okay, reverted back to CentOS 6 (and commented so next time we won't forget).

I install devtoolset 7 and build with it. Tested now on my CentOS 6 machine - works fine. Also, no `libstdc++.so` in `ldd`.

**Review by liorgorb — APPROVED** [review]

**Comment by Jongy** [comment]
Unrelated error..
```
[2021-07-13 13:31:19,608] ERROR: gprofiler.profiler_base: PySpyProfiler: failed to profile process 667
Traceback (most recent call last):
  File "gprofiler/profiler_base.py", line 111, in snapshot
  File "concurrent/futures/_base.py", line 425, in result
  File "concurrent/futures/_base.py", line 384, in __get_result
  File "concurrent/futures/thread.py", line 56, in run
  File "gprofiler/python.py", line 63, in _profile_process
  File "gprofiler/utils.py", line 146, in run_process
  File "subprocess.py", line 863, in communicate
  File "subprocess.py", line 1527, in _communicate
  File "selectors.py", line 351, in register
  File "selectors.py", line 237, in register
  File "selectors.py", line 224, in _fileobj_lookup
  File "selectors.py", line 39, in _fileobj_to_fd
ValueError: Invalid file object: <_io.BufferedReader name=18>
```

**Comment by Jongy** [comment]
Also checked my Java running on `java:latest` - it has `/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.20` loaded.

**Pull request merged**
