### PR TITLE
python: Get Python version in app metadata for uwsgi apps

### PR DESCRIPTION
**Pull request by Jongy**
Closes: #434

Tests:
* [x] uwsgi Python 2 - we get python version in app metadata
* [x] uwsgi Python 3 - we get python version in app metadata

### CODE REVIEW

**Comment by Jongy** [comment]
Works:
```
[2022-09-15 17:31:36,087] DEBUG: gprofiler.utils: Running command: (/proc/623/exe --python-version)
[2022-09-15 17:31:36,091] DEBUG: gprofiler.utils: (['/proc/623/exe', '--python-version']) exit code: 0
[2022-09-15 17:31:36,091] DEBUG: gprofiler.utils: (['/proc/623/exe', '--python-version']) stdout: '3.10.6\n'
```

**Comment by Jongy** [comment]
Also Python 2:
```
[2022-09-15 17:34:23,349] DEBUG: gprofiler.utils: Running command: (/proc/619/exe --python-version)
[2022-09-15 17:34:23,354] DEBUG: gprofiler.utils: (['/proc/619/exe', '--python-version']) exit code: 0
[2022-09-15 17:34:23,355] DEBUG: gprofiler.utils: (['/proc/619/exe', '--python-version']) stdout: '2.7.18\n'
```

**Comment by Jongy** [comment]
And we still get the `sys.maxunicode` correctly after my change (I don't recall if that's tested at the moment)
```
[2022-09-15 17:38:02,796] DEBUG: gprofiler.utils: Running command: (/proc/621/exe -S -c import sys; print(sys.maxunicode))
[2022-09-15 17:38:02,800] DEBUG: gprofiler.utils: (['/proc/621/exe', '-S', '-c', 'import sys; print(sys.maxunicode)']) exit code: 0
[2022-09-15 17:38:02,801] DEBUG: gprofiler.utils: (['/proc/621/exe', '-S', '-c', 'import sys; print(sys.maxunicode)']) stdout: '1114111\n'
```

**Review by netaneld122 — APPROVED** [review]
LGTM

**Comment by Jongy** [comment]
I'll add proper tests after https://github.com/Granulate/gprofiler/pull/478

**Comment by Jongy** [comment]
Failure is `ValueError: Invalid file object: <_io.BufferedReader name=44>` (python 3.6 bug)

**Pull request merged**
