### PR TITLE
Increase duration of gprofiler container in test_from_container_spawned_process test

### PR DESCRIPTION
**Pull request by mpozniak95**
## Description
Increasing duration of gprofiler container should avoid container stopping before application fibonacci starts.

## Related Issue
https://github.com/Granulate/gprofiler/issues/513

## How Has This Been Tested?
I added artificial delay to `_application_process` function by using `time.wait(10)` and then I ran the test_sanity.py.

### CODE REVIEW

**Comment by Jongy** [comment]
Created 2 tickets from the flaky failures, [1](https://github.com/Granulate/gprofiler/issues/537) [2](https://github.com/Granulate/gprofiler/issues/538)

**Comment by Jongy** [comment]
First run had 2 unrelated flaky errors: https://github.com/Granulate/gprofiler/actions/runs/3243777862/attempts/2
Invoked 2nd run now

**Comment by Jongy** [comment]
Merge master after #539 539

**Comment by mpozniak95** [comment]
Master merged

**Comment by Jongy** [comment]
Flaky failures: https://github.com/Granulate/gprofiler/issues/512 and #538

**Comment by Jongy** [comment]
I'll merge it now and if we stop seeing occurrences of https://github.com/Granulate/gprofiler/issues/513, we can close it.

**Review by Jongy — APPROVED** [review]

**Pull request merged**
