### PR TITLE
metrics: Fix timestamp

### PR DESCRIPTION
**Pull request by d3dave**
time.monotonic does not represent current time.

### CODE REVIEW

**Comment by d3dave** [comment]
@roi-granulate Please test, thanks.

**Review by Jongy — APPROVED** [review]
LGTM. What's between `datetime.now()` and `datetime.utcnow()` btw?

**Comment by d3dave** [comment]
> LGTM. What's between `datetime.now()` and `datetime.utcnow()` btw?

`utcnow()` returns a TZ-unaware object. `now()` returns a TZ-aware object. So if you try to get `timestamp()` of TZ-unaware object, it will assume it is in local time and you'd get a wrong result:

```python3
In [5]: datetime.now(tz=timezone.utc)
Out[5]: datetime.datetime(2023, 3, 6, 14, 8, 39, 670833, tzinfo=datetime.timezone.utc)

In [6]: _.timestamp()
Out[6]: 1678111719.670833

In [7]: datetime.utcnow()
Out[7]: datetime.datetime(2023, 3, 6, 14, 8, 48, 270091)

In [8]: _.timestamp()
Out[8]: 1678104528.270091
```

**Comment by Jongy** [comment]
> > LGTM. What's between `datetime.now()` and `datetime.utcnow()` btw?
> 
> `utcnow()` returns a TZ-unaware object. `now()` returns a TZ-aware object. So if you try to get `timestamp()` of TZ-unaware object, it will assume it is in local time and you'd get a wrong result:
> 
> ```python
> In [5]: datetime.now(tz=timezone.utc)
> Out[5]: datetime.datetime(2023, 3, 6, 14, 8, 39, 670833, tzinfo=datetime.timezone.utc)
> 
> In [6]: _.timestamp()
> Out[6]: 1678111719.670833
> 
> In [7]: datetime.utcnow()
> Out[7]: datetime.datetime(2023, 3, 6, 14, 8, 48, 270091)
> 
> In [8]: _.timestamp()
> Out[8]: 1678104528.270091
> ```

Oh wow. TIL

**Review by roi-granulate — APPROVED** [review]
Tested and LGTM

**Pull request merged**
